version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: saas_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: saas_db_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - saas_dev_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: saas_backend_dev
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/saas_db_dev
      - SECRET_KEY=dev-secret-key
      - DEBUG=true
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
    networks:
      - saas_dev_network
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

volumes:
  postgres_dev_data:
    driver: local

networks:
  saas_dev_network:
    driver: bridge
